const cards = [
    { name: "The Fool", meaning: "The Fool meaning placeholder." },
    { name: "The Magician", meaning: "The Magician meaning placeholder." },
    { name: "The High Priestess", meaning: "The High Priestess meaning placeholder." },
    { name: "The Empress", meaning: "The Empress meaning placeholder." },
    { name: "The Emperor", meaning: "The Emperor meaning placeholder." },
    { name: "The Hierophant", meaning: "The Hierophant meaning placeholder." },
    { name: "The Lovers", meaning: "The Lovers meaning placeholder." },
    { name: "The Chariot", meaning: "The Chariot meaning placeholder." },
    { name: "Strength", meaning: "Strength meaning placeholder." },
    { name: "The Hermit", meaning: "The Hermit meaning placeholder." },
    { name: "Wheel of Fortune", meaning: "Wheel of Fortune meaning placeholder." },
    { name: "Justice", meaning: "Justice meaning placeholder." },
    { name: "The Hanged Man", meaning: "The Hanged Man meaning placeholder." },
    { name: "Death", meaning: "Death meaning placeholder." },
    { name: "Temperance", meaning: "Temperance meaning placeholder." },
    { name: "The Devil", meaning: "The Devil meaning placeholder." },
    { name: "The Tower", meaning: "The Tower meaning placeholder." },
    { name: "The Star", meaning: "The Star meaning placeholder." },
    { name: "The Moon", meaning: "The Moon meaning placeholder." },
    { name: "The Sun", meaning: "The Sun meaning placeholder." },
    { name: "Judgement", meaning: "Judgement meaning placeholder." },
    { name: "The World", meaning: "The World meaning placeholder." },
    { name: "Ace of Wands", meaning: "Ace of Wands meaning placeholder." },
    { name: "Two of Wands", meaning: "Two of Wands meaning placeholder." },
    { name: "Three of Wands", meaning: "Three of Wands meaning placeholder." },
    { name: "Four of Wands", meaning: "Four of Wands meaning placeholder." },
    { name: "Five of Wands", meaning: "Five of Wands meaning placeholder." },
    { name: "Six of Wands", meaning: "Six of Wands meaning placeholder." },
    { name: "Seven of Wands", meaning: "Seven of Wands meaning placeholder." },
    { name: "Eight of Wands", meaning: "Eight of Wands meaning placeholder." },
    { name: "Nine of Wands", meaning: "Nine of Wands meaning placeholder." },
    { name: "Ten of Wands", meaning: "Ten of Wands meaning placeholder." },
    { name: "Page of Wands", meaning: "Page of Wands meaning placeholder." },
    { name: "Knight of Wands", meaning: "Knight of Wands meaning placeholder." },
    { name: "Queen of Wands", meaning: "Queen of Wands meaning placeholder." },
    { name: "King of Wands", meaning: "King of Wands meaning placeholder." },
    { name: "Ace of Cups", meaning: "Ace of Cups meaning placeholder." },
    { name: "Two of Cups", meaning: "Two of Cups meaning placeholder." },
    { name: "Three of Cups", meaning: "Three of Cups meaning placeholder." },
    { name: "Four of Cups", meaning: "Four of Cups meaning placeholder." },
    { name: "Five of Cups", meaning: "Five of Cups meaning placeholder." },
    { name: "Six of Cups", meaning: "Six of Cups meaning placeholder." },
    { name: "Seven of Cups", meaning: "Seven of Cups meaning placeholder." },
    { name: "Eight of Cups", meaning: "Eight of Cups meaning placeholder." },
    { name: "Nine of Cups", meaning: "Nine of Cups meaning placeholder." },
    { name: "Ten of Cups", meaning: "Ten of Cups meaning placeholder." },
    { name: "Page of Cups", meaning: "Page of Cups meaning placeholder." },
    { name: "Knight of Cups", meaning: "Knight of Cups meaning placeholder." },
    { name: "Queen of Cups", meaning: "Queen of Cups meaning placeholder." },
    { name: "King of Cups", meaning: "King of Cups meaning placeholder." },
    { name: "Ace of Swords", meaning: "Ace of Swords meaning placeholder." },
    { name: "Two of Swords", meaning: "Two of Swords meaning placeholder." },
    { name: "Three of Swords", meaning: "Three of Swords meaning placeholder." },
    { name: "Four of Swords", meaning: "Four of Swords meaning placeholder." },
    { name: "Five of Swords", meaning: "Five of Swords meaning placeholder." },
    { name: "Six of Swords", meaning: "Six of Swords meaning placeholder." },
    { name: "Seven of Swords", meaning: "Seven of Swords meaning placeholder." },
    { name: "Eight of Swords", meaning: "Eight of Swords meaning placeholder." },
    { name: "Nine of Swords", meaning: "Nine of Swords meaning placeholder." },
    { name: "Ten of Swords", meaning: "Ten of Swords meaning placeholder." },
    { name: "Page of Swords", meaning: "Page of Swords meaning placeholder." },
    { name: "Knight of Swords", meaning: "Knight of Swords meaning placeholder." },
    { name: "Queen of Swords", meaning: "Queen of Swords meaning placeholder." },
    { name: "King of Swords", meaning: "King of Swords meaning placeholder." },
    { name: "Ace of Pentacles", meaning: "Ace of Pentacles meaning placeholder." },
    { name: "Two of Pentacles", meaning: "Two of Pentacles meaning placeholder." },
    { name: "Three of Pentacles", meaning: "Three of Pentacles meaning placeholder." },
    { name: "Four of Pentacles", meaning: "Four of Pentacles meaning placeholder." },
    { name: "Five of Pentacles", meaning: "Five of Pentacles meaning placeholder." },
    { name: "Six of Pentacles", meaning: "Six of Pentacles meaning placeholder." },
    { name: "Seven of Pentacles", meaning: "Seven of Pentacles meaning placeholder." },
    { name: "Eight of Pentacles", meaning: "Eight of Pentacles meaning placeholder." },
    { name: "Nine of Pentacles", meaning: "Nine of Pentacles meaning placeholder." },
    { name: "Ten of Pentacles", meaning: "Ten of Pentacles meaning placeholder." },
    { name: "Page of Pentacles", meaning: "Page of Pentacles meaning placeholder." },
    { name: "Knight of Pentacles", meaning: "Knight of Pentacles meaning placeholder." },
    { name: "Queen of Pentacles", meaning: "Queen of Pentacles meaning placeholder." },
    { name: "King of Pentacles", meaning: "King of Pentacles meaning placeholder." },
];